name: Deploy NPMJS
on:
  push:
    branches:
      - 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'NPMJS') }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - run: git config --global user.email "jeonghyeon.rhea@gmail.com"
      - run: git config --global user.name "rhea-so"
      - run: npm version patch -f
      - run: git commit --amend -m "NPMJS Publish - ${{github.event.head_commit.message}}"
      - name: Publish Packages
        run: |
          echo '//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN  }}' > .npmrc
          cat .npmrc
      - run: npm run publish
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPO_PAT }}
          branch: ${{ github.ref }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
