name: Deploy NPMJS
on:
  push:
    branches:
      - 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'NPMJS') }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - run: git config --global user.email "jeonghyeon.rhea@gmail.com"
      - run: git config --global user.name "rhea-so"
      - run: npm version patch -f
      - run: git init
      - run: git add .
      - run: git commit --amend -m "NPMJS Publish - ${{github.event.head_commit.message}}"
      - run: git remote remove origin
      - run: git remote add origin https://${{ secrets.REPO_PAT }}@github.com/rhea-so-lab/env-typescript.git
      - run: git push -u origin production
      - run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
